services:
  - type: web
    name: deep-research-agent
    runtime: python
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn serve:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: "10000"
