import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface RenderRequest {
  animationScript: string;  // React TSX code for Remotion composition
  slideId: string;          // Unique identifier for the slide (e.g., "pitchDeckId-slide-3")
  compositionConfig: {
    id: string;             // Composition ID (e.g., "slide-3")
    fps: number;            // Frame rate (default: 30)
    durationInFrames: number; // Total frames (e.g., 240 for 8 seconds @ 30fps)
    width: number;          // Video width (default: 1920)
    height: number;         // Video height (default: 1080)
  };
}

interface RenderResponse {
  videoUrl?: string;        // Public URL to the rendered MP4
  duration?: number;        // Video duration in seconds
  fileSizeMb?: number;      // File size in megabytes
  error?: string;           // Error message if rendering failed
}

/**
 * Remotion Video Rendering Edge Function
 *
 * This function takes Remotion TSX code generated by generate-pitch-deck
 * and renders it to an MP4 video file.
 *
 * **IMPLEMENTATION STATUS**: Placeholder (Phase 7)
 *
 * **CHALLENGE**: Remotion's @remotion/renderer requires Node.js, but Supabase
 * Edge Functions run on Deno. This creates a compatibility issue.
 *
 * **SOLUTION OPTIONS**:
 *
 * 1. **Node.js Docker Container** (Recommended)
 *    - Deploy separate Node.js service (e.g., Cloud Run, Fly.io)
 *    - This Edge Function acts as a proxy/orchestrator
 *    - Calls the Node.js service for actual rendering
 *    - Handles Supabase Storage upload
 *
 * 2. **Deno-Compatible Alternative**
 *    - Explore deno-compatible video rendering libraries
 *    - May have limited capabilities compared to Remotion
 *    - Would require rewriting animation generation prompts
 *
 * 3. **External Rendering Service**
 *    - Use Remotion Lambda (AWS) or Remotion Cloud
 *    - Higher cost but managed infrastructure
 *    - Requires Remotion Cloud API key
 *
 * **CURRENT IMPLEMENTATION**: Option 1 approach with placeholder
 *
 * For MVP, this function:
 * - Accepts Remotion scripts and configuration
 * - Stores animation script in Supabase Storage (for future rendering)
 * - Returns error indicating video rendering is not yet implemented
 * - Allows the rest of the pipeline to function without blocking
 */

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('No authorization header');
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Verify user
    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    if (authError || !user) {
      throw new Error('Unauthorized');
    }

    const {
      animationScript,
      slideId,
      compositionConfig
    }: RenderRequest = await req.json();

    console.log('Remotion video rendering request:', {
      slideId,
      scriptLength: animationScript.length,
      config: compositionConfig
    });

    // Validate required parameters
    if (!animationScript || !slideId || !compositionConfig) {
      throw new Error('Missing required parameters: animationScript, slideId, or compositionConfig');
    }

    // TODO: Implement video rendering pipeline
    //
    // **Step 1: Write animation script to temp file**
    // const tempDir = await Deno.makeTempDir();
    // const componentPath = `${tempDir}/SlideAnimation.tsx`;
    // await Deno.writeTextFile(componentPath, animationScript);
    //
    // **Step 2: Bundle Remotion project**
    // NOTE: This requires @remotion/bundler which is Node.js only
    // const bundled = await bundle(componentPath);
    //
    // **Step 3: Select composition**
    // NOTE: This requires @remotion/renderer which is Node.js only
    // const composition = await selectComposition({
    //   serveUrl: bundled,
    //   id: compositionConfig.id,
    // });
    //
    // **Step 4: Render video to MP4**
    // NOTE: This requires @remotion/renderer which is Node.js only
    // const outputPath = `${tempDir}/output.mp4`;
    // await renderMedia({
    //   composition,
    //   serveUrl: bundled,
    //   codec: 'h264',
    //   outputLocation: outputPath,
    // });
    //
    // **Step 5: Upload to Supabase Storage**
    // const videoFile = await Deno.readFile(outputPath);
    // const { data, error } = await supabase.storage
    //   .from('pitch-deck-videos')
    //   .upload(`${slideId}.mp4`, videoFile, {
    //     contentType: 'video/mp4',
    //     cacheControl: '3600',
    //     upsert: true,
    //   });
    //
    // if (error) {
    //   throw new Error(`Storage upload failed: ${error.message}`);
    // }
    //
    // **Step 6: Get public URL**
    // const { data: { publicUrl } } = supabase.storage
    //   .from('pitch-deck-videos')
    //   .getPublicUrl(`${slideId}.mp4`);
    //
    // **Step 7: Cleanup temp files**
    // await Deno.remove(tempDir, { recursive: true });

    // PLACEHOLDER: Store animation script for future rendering
    // This allows the pipeline to function while video rendering is being implemented
    try {
      const scriptFileName = `${slideId}-animation-script.tsx`;
      const { error: uploadError } = await supabase.storage
        .from('pitch-deck-videos')
        .upload(scriptFileName, animationScript, {
          contentType: 'text/typescript',
          cacheControl: '3600',
          upsert: true,
        });

      if (uploadError) {
        console.error('Failed to store animation script:', uploadError);
      } else {
        console.log(`Animation script stored: ${scriptFileName}`);
      }
    } catch (error) {
      console.error('Error storing animation script:', error);
    }

    // Return placeholder response indicating rendering is not yet implemented
    const response: RenderResponse = {
      error: 'Video rendering not yet implemented (Remotion requires Node.js, Edge Functions use Deno). Animation script has been stored for future rendering.',
      videoUrl: undefined,
      duration: compositionConfig.durationInFrames / compositionConfig.fps,
      fileSizeMb: undefined
    };

    console.log('Remotion rendering status:', response);

    return new Response(
      JSON.stringify(response),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200, // Return 200 even though rendering failed, to not block the pipeline
      }
    );

  } catch (error) {
    console.error('Remotion rendering error:', error);

    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        videoUrl: undefined
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    );
  }
});

/**
 * NEXT STEPS FOR FULL IMPLEMENTATION:
 *
 * 1. **Set up Node.js rendering service**:
 *    - Create separate Node.js service (e.g., Express + Remotion renderer)
 *    - Deploy to Cloud Run, Fly.io, or similar
 *    - Expose POST /render endpoint
 *
 * 2. **Update this Edge Function**:
 *    - Call Node.js service from this function
 *    - Handle rendering job status polling
 *    - Upload rendered MP4 to Supabase Storage
 *    - Return public URL
 *
 * 3. **Add job queue (optional)**:
 *    - Use BullMQ or similar for async rendering
 *    - Store rendering status in Supabase
 *    - Add webhook for completion notification
 *
 * 4. **Cost optimization**:
 *    - Cache rendered videos (don't re-render unchanged slides)
 *    - Compress videos (target <5MB per slide)
 *    - Monitor rendering costs
 *
 * 5. **Error handling**:
 *    - Retry logic for failed renders
 *    - Fallback to static images
 *    - Alert on repeated failures
 */
